import type { Metadata } from "next";
import "./globals.css";
import SessionContextProvider from "../context/SessionProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black text-white">
        <SessionContextProvider>{children}</SessionContextProvider>
      </body>
    </html>
  );
}
