FROM oven/bun:1

ENV DATABASE_URL=${DATABASE_URL}

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/backend ./apps/backend

RUN bun install

RUN bun run generate:db

EXPOSE 3002

CMD ["bun", "start:backend"]