name: Continuous Deployment (Frontend)
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Docker login
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push the image
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.frontend
          push: true
          tags: souravbhowal/excalibur_frontend:${{ github.sha }}
          
      # SSH into the server and pull the image and run the container
      - name: SSH into the server and pull the image and run the container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker stop excalibur_frontend
            docker rm excalibur_frontend
            docker pull souravbhowal/excalibur_frontend:${{ github.sha }}
            docker run --name excalibur_frontend -d -p 3000:3000 souravbhowal/excalibur_frontend:${{ github.sha }}

      